language: php

php:
    - 5.5
    - 5.4
    - 5.3

before_install:
    - set -ex
    # - composer install
    # set up wp-cli
    - export VERSION="dev-master"
    - export WP_CORE_DIR="/tmp/wordpress"
    - mkdir $WP_CORE_DIR
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

before_script:
    - cd $TRAVIS_BUILD_DIR
    - composer install --dev --no-interaction --prefer-source
    - export PATH="$TRAVIS_BUILD_DIR/vendor/bin/:$PATH"
    - cd $WP_CORE_DIR
    - wp proxy install --sudo
    - wp proxy version


script:
    - exit 0